### PR TITLE
Add Portuguese Pt-Br translation

### PR DESCRIPTION
**Pull request by maisondasilva**
Add PtBR

### CODE REVIEW

**Comment by tnhung2011** [comment]
I didn't know what's **"PtBR"** is, I checked the files and realized this is a Portuguese translation. Please rename this pull request to **"Add Portuguese translation"** or **"Please add Portuguese translation"**.

**Comment by maisondasilva** [comment]
There are two types of Portuguese, Brazilian Portuguese ptbr and Portuguese from Portugal ptpt so I put ptbr because the translations of several words are different.

https://www.quora.com/What-are-differences-between-Portugals-Portuguese-language-and-Brazils-Portuguese-language

Thank

**Comment by maisondasilva** [comment]
PT-PT versus PT-BR

https://www.translatorscafe.com/cafe/MegaBBS/forumthread956.htm

**Comment by SamuelTulach** [comment]
Thanks!

**Pull request merged**
