### PR TITLE
Icon in Remove Program #103

### PR DESCRIPTION
**Pull request by maisondasilva**
Icon in Remove Program #103

### CODE REVIEW

**Review by tnhung2011 — CHANGES_REQUESTED** [review]
I can't get rid of this comment so yeah. https://github.com/SamuelTulach/VirusTotalUploader/issues/103
(I moved my comment to that related issue page)

**Comment by maisondasilva** [comment]
> I can't get rid of this comment so yeah. #103

I didn't understand this comment

**Comment by tnhung2011** [comment]
> > I can't get rid of this comment so yeah. #103
> 
> I didn't understand this comment

That literally means that I moved that comment to https://github.com/SamuelTulach/VirusTotalUploader/issues/103.

XD

**Comment by maisondasilva** [comment]
fix version 2.0

**Pull request closed without merging**
